% (c) 2025, Chenbo Shi, UESTC in China
function write_prefeko(prePath, cards, f0, portInfo, pwInfo)
%WRITE_PRE  Generate FEKO .pre file (only essential cards)
%
% write_pre(prePath, cards)
%
% Inputs:
%   prePath : Output .pre file path (char/string)
%   cards   : Struct, must contain the following fields (case-sensitive):
%             SF (char/string; single line)
%             IN (string/cellstr; multiple lines)
%             DP (string/cellstr; multiple lines)
%             EG (char/string; single line)
%             PS (char/string; single line)
%             CG (char/string; single line)
%             DI (string/cellstr; multiple lines)
%
% Notes:
% - This function does not change the content of the given lines. It outputs
%   exactly what you pass in (automatically appends newline at the end).
% - Output order is: SF, IN, DP, EG, PS, CG, AW, DI.
% - If a certain type is empty, a comment placeholder line will be written
%   (to satisfy the "must output" requirement). You can also change this to
%   throw an error if desired.

requiredFields = {'SF','IN','DP','EG','PS','CG','DI','FP'};
% Basic validation
for k = 1:numel(requiredFields)
    f = requiredFields{k};
    if ~isfield(cards, f)
        error('write_pre:MissingField', '缺少必需字段 "%s".', f);
    end
end

% Open file
[fid, msg] = fopen(prePath, 'w');
if fid < 0
    error('write_pre:IO', '无法打开文件 "%s": %s', prePath, msg);
end
cleaner = onCleanup(@() fclose(fid));

% Helper: convert char/cellstr/string into a column string array
toStrCol = @(x) reshape(string(x), [], 1);

% Optional header line
fprintf(fid, '** Generated by write_pre.m\n');

% ---- Output in the specified order ----
% 1) SF (single line)
writeOne(fid, cards.SF, 'SF');

% 2) IN (single line)
writeOne(fid, cards.IN, 'IN');

% 3) DP (multiple lines)
writeMany(fid, cards.DP, 'DP');

% 4) FP (single line)
writeOne(fid, cards.FP, 'FP');

% 5) EG (single line)
writeOne(fid, cards.EG, 'EG');

% 6) PS (single line)
writeOne(fid, cards.PS, 'PS');

% 7) CG (single line)
writeOne(fid, cards.CG, 'CG');

% 8) DI (multiple lines)
writeMany(fid, cards.DI, 'DI');

% Write frequency information
% === FR: write frequency card ===
if isempty(f0)
    fprintf(fid, '** FR: (no frequency defined)\n');
else
    f0 = f0(:);
    N = numel(f0);
    % First line
    fprintf(fid, 'FR: %d : 3 :  :  :  : %.15g\n', N, f0(1));
    % Subsequent frequency lines
    for k = 2:N
        fprintf(fid, '  :  :  :  :  :  : %.15g\n', f0(k));
    end
end

%% Excitations for all propagation modes on all ports
% ===== Collect all modal information from all ports into global lists,
%       then use macro arrays + a single for-loop to generate AW cards =====
if exist('portInfo','var') && ~isempty(portInfo)

    % 1) Collect per-port static information (string constants & point labels)
    Np = numel(portInfo);
    pts4 = strings(Np,4);
    faceStr = strings(Np,1);
    medStr  = strings(Np,1);
    wType = zeros(Np,1);
    % Magnitude / phase
    magV  = ones(Np,1);
    phsV  = zeros(Np,1);

    for ii = 1:Np
        % Geometry face label
        if isfield(portInfo(ii),'faceLabel') && ~isempty(portInfo(ii).faceLabel)
            faceStr(ii) = string(portInfo(ii).faceLabel);
        else
            faceStr(ii) = "";
        end

        % Medium label
        if isfield(portInfo(ii),'mediumLabel') && ~isempty(portInfo(ii).mediumLabel)
            medStr(ii) = string(portInfo(ii).mediumLabel);
        else
            medStr(ii) = "";
        end

        % Waveguide type code
        if isfield(portInfo(ii),'typeCode') && ~isempty(portInfo(ii).typeCode)
            wType(ii) = portInfo(ii).typeCode;
        else
            wType(ii) = 0;
        end

        % Point labels (up to 4; remaining slots left empty)
        if isfield(portInfo(ii),'ptLabs') && ~isempty(portInfo(ii).ptLabs)
            p = string(portInfo(ii).ptLabs(:).');
            k = min(4, numel(p));
            pts4(ii,1:k) = p(1:k);
        end
    end

    % 2) Flatten modes into global arrays: #p, #tem, #m, #n
    %    Also compute global total count N_all
    p_all   = []; tem_all = []; m_all = []; n_all = [];
    for ii = 1:Np
        if isfield(portInfo(ii),'modesList') && ~isempty(portInfo(ii).modesList)
            M = portInfo(ii).modesList;  % [typeCode, m, n]
            nrow = size(M,1);
            p_all   = [p_all;   ii*ones(nrow,1)]; %#ok<AGROW>
            tem_all = [tem_all; M(:,1)];         %#ok<AGROW>
            m_all   = [m_all;   M(:,2)];         %#ok<AGROW>
            n_all   = [n_all;   M(:,3)];         %#ok<AGROW>
        end
    end
    N_all = numel(tem_all);

    if N_all == 0
        fprintf(fid, '** AW: (no modes to excite)\n');
    else
        % Write port S-parameters
        PORT{1} = sprintf('\n** S-parameters\n');
        % PORT{end+1} = sprintf('NC: SParameterConfig\n');
        PORT{end+1} = sprintf('DA: 0 : 0 : 0 : 0 : 0 : 1 :  :  : 0\n');
        for ii = 1:Np % Loop over each port
            fs  = char(faceStr(ii));
            md  = char(medStr(ii));
            tc  = wType(ii);
            mg  = magV(ii);
            ph  = phsV(ii);
            p1  = char(pts4(ii,1));  p2 = char(pts4(ii,2));
            p3  = char(pts4(ii,3));  p4 = char(pts4(ii,4));
            for k = 1:N_all
                avtive = (k~=1);
                PORT{end+1} = sprintf('AW: %d : %s : %d : %s : 0 : %.15g : %.15g : %s : %s : %s : %s : 0\n', ...
                    avtive, fs, tc, md, mg, ph, p1, p2, p3, p4);
                PORT{end+1} = sprintf('  : %d : -1 : -1 : %d : %d\n',tem_all(k), m_all(k), n_all(k));
            end
        end
        PORT{end+1} = 'SP: 1 : 1   ** SPara\n';        
        % PORT{end+1} = 'NC: StandardConfig\n';

        fprintf(fid, [PORT{:}]);
%%
        % 3) Write global lists into the .pre file
        fprintf(fid, '** ==== Global mode lists for all ports ====\n');
        fprintf(fid, '#N_all = %d\n', N_all);
        for k = 1:N_all
            portIdx = p_all(k);
            fprintf(fid, '#p[%d]   = %d   ** Port %d (%s)\n', ...
                k, portIdx, portIdx, char(faceStr(portIdx)));
            fprintf(fid, '#tem[%d] = %d\n',   k, tem_all(k)); % 1=TE,2=TM,3=TEM
            fprintf(fid, '#m[%d]   = %d\n',   k, m_all(k));
            fprintf(fid, '#n[%d]   = %d\n',   k, n_all(k));
        end

        % 4) Single macro loop; branch to each port to write AW
        %    (idx fixed to 0; single-line AW format)
        % ===== Single macro loop (no indentation, strict 2-line AW format,
        %       complete endif structure) =====
        fprintf(fid, '!! for #k = 1 to #N_all step 1\n');
        fprintf(fid, 'PW: 1 : 0 : : : : 0.5 ** normalized power\n');

        for ii = 1:Np
            fs  = char(faceStr(ii));
            md  = char(medStr(ii));
            tc  = wType(ii);
            mg  = magV(ii);
            ph  = phsV(ii);
            p1  = char(pts4(ii,1));  p2 = char(pts4(ii,2));
            p3  = char(pts4(ii,3));  p4 = char(pts4(ii,4));

            if ii == 1
                fprintf(fid, '!! if #p[#k] = %d then\n', ii);
            else
                fprintf(fid, '!! else\n');
                fprintf(fid, '!! if #p[#k] = %d then\n', ii);
            end

            % -- TEM=1 (TE) --
            fprintf(fid, '!! if #tem[#k] = 1 then\n');
            fprintf(fid, 'AW: 0 : %s : %d : %s : 0 : %.15g : %.15g : %s : %s : %s : %s : 0\n', ...
                fs, tc, md, mg, ph + 90, p1, p2, p3, p4); % for FEKO TE modes, 90 degrees phase shift is needed.
            fprintf(fid, '  : 1 : -1 : -1 : #m[#k] : #n[#k]\n');

            % -- TEM=2 (TM) --
            fprintf(fid, '!! else\n');
            fprintf(fid, '!! if #tem[#k] = 2 then\n');
            fprintf(fid, 'AW: 0 : %s : %d : %s : 0 : %.15g : %.15g : %s : %s : %s : %s : 0\n', ...
                fs, tc, md, mg, ph + 90, p1, p2, p3, p4);  % for FEKO TM modes, 90 degrees phase shift is needed.
            fprintf(fid, '  : 2 : -1 : -1 : #m[#k] : #n[#k]\n');

            % -- TEM=3 (TEM) --
            fprintf(fid, '!! else\n');
            fprintf(fid, '!! if #tem[#k] = 3 then\n');
            fprintf(fid, 'AW: 0 : %s : %d : %s : 0 : %.15g : %.15g : %s : %s : %s : %s : 0\n', ...
                fs, tc, md, mg, ph, p1, p2, p3, p4);
            fprintf(fid, '  : 3 : -1 : -1 : #m[#k] : #n[#k]\n');

            % Close the three TEM branches
            fprintf(fid, '!! endif\n');
            fprintf(fid, '!! endif\n');
            fprintf(fid, '!! endif\n');
        end

        % Close the port if-ladder (repeated Np times)
        for ii = 1:Np
            fprintf(fid, '!! endif\n');
        end

        % At the end of the loop, append DA/OF/FF using your template
        % (no indentation, starting from first column)
        % Set far field points
        nFF = size(pwInfo.FF, 1);
        FRF = cell(3 + nFF, 1);
        FRF{1} = sprintf('\n** Far fields: Radiation\n');
        FRF{2} = sprintf('DA:  :  : 1 :  : 0 :  : 0\n');
        FRF{3} = sprintf('OF: 1 : 0 :  :  :  : 0 : 0 : 0 : 0 : 0 : 0\n');

        for n = 1:nFF
            % Scattered field only:
            FRF{3+n} = sprintf(...
                'FF: -1 : 1 : 1 : 0 : 0 : %1.3f : %1.3f : 0 : 0   ** PortFarField%d\n', ...
                pwInfo.FF(n, 1), pwInfo.FF(n, 2), n);
        end
        fprintf(fid, [FRF{:}]);
        fprintf(fid, '!! next\n');

    end
else
    fprintf(fid, '** AW: (no waveguide excitations; portInfo not provided)\n');
end

%% Plane-wave excitations (Lebedev points)
% Define angles
ANG{1} = sprintf('\n** Array of incident theta and phi angles to solve\n');
nAngles = size(pwInfo.PW, 1);
for thisAngle = 1:nAngles
    Theta{thisAngle} = sprintf('#theta[%d] = %1.6f\n', thisAngle, pwInfo.PW(thisAngle, 1));
    Phi{thisAngle}   = sprintf('#phi[%d] = %1.6f\n', thisAngle, pwInfo.PW(thisAngle, 2));
    Pol{thisAngle}   = sprintf('#pol[%d] = %1.6f\n', thisAngle, pwInfo.PW(thisAngle, 3));
end
ANG = [ANG, Theta, {'\n'}, Phi, {'\n'}, Pol];
fprintf(fid, [ANG{:}]);

% Set sources (plane waves)
SR_A{1} = sprintf('\n** Sources\n');

SR_A{2} = sprintf('!! for #k = 1 to %d step 1\n\n', nAngles);
SR_A{3} = sprintf('PW: 0 : 0\n');
SR_A{4} = sprintf(...
    'A0: 0 : 0 : 1 : 1 : 1 : 1 : 0 : #theta[#k] : #phi[#k] : #pol[#k] : 0 : 0\n', ...
    pwInfo.PW(1), pwInfo.PW(2), pwInfo.PW(3));
SR_A{5} = sprintf('  : 0 :  :  :  :  :  :  : 0 : 0 : 0 : 0 : 0 : 0\n');

% Set far field points
nFF = size(pwInfo.FF, 1);
FRF = cell(3 + nFF, 1);
FRF{1} = sprintf('\n** Far fields: FarFields\n');
FRF{2} = sprintf('DA:  :  : 1 :  : 0 :  : 0\n');
FRF{3} = sprintf('OF: 1 : 0 :  :  :  : 0 : 0 : 0 : 0 : 0 : 0\n');
% FRF{4} = sprintf('FF: 1 : 181 : 181 : 0 : 0 : 0 : 0 : 2 : 2 :  :  : 0 ** sca_Farfield\n');

for n = 1:nFF
    % Scattered field only:
    FRF{3+n} = sprintf(...
        'FF: -1 : 1 : 1 : 0 : 0 : %1.3f : %1.3f : 0 : 0   ** FarField%d\n', ...
        pwInfo.FF(n, 1), pwInfo.FF(n, 2), n);
end

SR_B{1} = sprintf('\n!! next ** (theta,phi,pol)\n');

fprintf(fid, [SR_A{:}]);
fprintf(fid, [FRF{:}]);
fprintf(fid, [SR_B{:}]);
% End marker (optional)
fprintf(fid, '** End of file\n');
fprintf(fid, 'EN\n');

%% ===== Local helper functions =====
    function writeOne(fid_, val, tag)
        % Write a single-line card; if empty, write a commented placeholder
        % to satisfy the "must output" requirement
        if isempty(val)
            fprintf(fid_, '** %s: (empty)\n', tag);
            return
        end
        ln = string(val);
        if ismissing(ln) || strlength(ln) == 0
            fprintf(fid_, '** %s: (empty)\n', tag);
        else
            % Output as is (if the line does not start with the tag, it will
            % not be corrected here)
            fprintf(fid_, '%s\n', ln);
        end
    end

    function writeMany(fid_, vals, tag)
        % Write a multi-line card; if no content, write a commented placeholder
        if isempty(vals)
            fprintf(fid_, '** %s: (no entries)\n', tag);
            return
        end
        arr = toStrCol(vals);
        if isempty(arr)
            fprintf(fid_, '** %s: (no entries)\n', tag);
            return
        end
        for ii = 1:numel(arr)
            ln = arr(ii);
            if ismissing(ln) || strlength(ln) == 0
                % Also output blank lines to preserve the line count; you can
                % change this to comment lines if you prefer
                fprintf(fid_, '\n');
            else
                fprintf(fid_, '%s\n', ln);
            end
        end
    end
end
